sudo: false
cache: bundler
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head
gemfile:
  - Gemfile
  - gemfiles/Gemfile-rails-5-0
  - gemfiles/Gemfile-rails-5-2
  - gemfiles/Gemfile-rails-master
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
env:
  global:
    - "JRUBY_OPTS=-Xcext.enabled=true"
