sudo: false
cache: bundler
rvm:
  - 2.2
  - 2.3.0
  - jruby
  - rbx-2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
env:
  global:
    - "JRUBY_OPTS=-Xcext.enabled=true"
